name: climate-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.10
  - panel
  - bokeh
  - intake
  - intake-xarray
  - xarray
  - netCDF4
  - dask
  - matplotlib
  - pandas
  - jupyterlab
  - jupyter-server-proxy

