#!/bin/bash
set -e

echo "Running .binder/start"
pwd
ls -l

# start Jupyter so Binder is happy
#jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password='' &

sleep 5

echo "Starting panel serve..."
ls -l data_catalog_app.py
panel serve data_catalog_app.py --address=0.0.0.0 --port=5006 --allow-websocket-origin="*"

