#!/bin/bash
set -eux

echo "Running .binder/start"
pwd
ls -l

echo "Starting Jupyter Lab"
jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password='' &

sleep 15

echo "Starting panel serve..."
panel serve data_catalog_app.py --address=0.0.0.0 --port=5006 --allow-websocket-origin="*" --log-level=debug

